project:
  type: website
  output-dir: docs

website:
  title: '<img src="other/logo.png" alt=""> CICLISMO REALE'
  favicon: "other/logo.png"
  navbar:
    pinned: true
    left:
      - classifica.qmd
      - squadre.qmd
      - cq_ranking.qmd
    right:
      - current_cq_ranking.qmd
      - medagliere.qmd
  announcement: 
    icon: info-circle
    dismissable: false
    content: "Sistemone in costruzione, portate pazienza!"
    type: primary
    position: below-navbar

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
    grid: 
      body-width: 1000px
      sidebar-width: 70px
      margin-width: 350px


